/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
import { make } from "../make"
import { random } from "../random"

/** Class for generating arrays. */
export class arrays {
  /**
   * Returns an array containing random values generated by the supplied function.
   *
   * @param fn - Function used to generate values.
   * @param limit - Length of the array.
   */
  static filledArray(fn: () => any, limit = make.numbers.tiny()): any[] {
    const array: any[] = []

    for (let i = 0; i < limit; i++) {
      const value = random.pick(fn)
      if (value !== null) {
        array.push(value)
      }
    }

    return array
  }
}
