version: 1
policy:
  pullRequests: collaborators
tasks:
  $let:
    user: ${event.sender.login}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}
    fetch_ref:
      $if: 'tasks_for == "github-pull-request"'
      then: "pull/${event.number}/head"
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: "tags/${event.release.tag_name}"

    http_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}

    ssh_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.base.repo.ssh_url}
      else: ${event.repository.ssh_url}

    secret_url:
      http://taskcluster/secrets/v1/secret/project/fuzzing/deploy-octo-private

  in:
    $if: 'tasks_for in ["github-pull-request", "github-push"]'
    then:
      $map:
        - 10
        - 12
      each(nodever):
        provisionerId: proj-fuzzing
        workerType: ci
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        scopes: [secrets:get:project/fuzzing/deploy-octo-private]
        payload:
          maxRunTime: 3600
          image: mozillasecurity/ci-node-${nodever}
          features:
            taskclusterProxy: true
          command:
            - /bin/bash
            - '--login'
            - '-x'
            - '-c'
            - >-
              curl -L ${secret_url} | jshon -e secret -e key -u > .ssh/id_rsa &&
              chmod 0400 .ssh/id_rsa &&
              git init repo &&
              cd repo &&
              git remote add origin ${ssh_repo} &&
              git fetch -q --depth=10 origin "${fetch_ref}" &&
              git -c advice.detachedHead=false checkout ${head_rev} &&
              npm i &&
              npm test
        metadata:
          name: octo-private tests nodejs ${nodever}
          description: octo-private tests nodejs ${nodever}
          owner: '${event.sender.login}@users.noreply.github.com'
          source: ${http_repo}/raw/${head_rev}/.taskcluster.yml

