version: 1
policy:
  pullRequests: collaborators
tasks:
  $let:
    user: ${event.sender.login}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}
    fetch_ref:
      $if: 'tasks_for == "github-pull-request"'
      then: "pull/${event.number}/head"
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: "tags/${event.release.tag_name}"

    http_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}

    ssh_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.base.repo.ssh_url}
      else: ${event.repository.ssh_url}

    commit_msg:
      $if: 'tasks_for == "github-push" && len(event.commits) == 1'
      then: ${event.commits[0].message}
      else: ''

    octo_deploy_url:
      http://taskcluster/secrets/v1/secret/project/fuzzing/deploy-octo
    npm_deploy_url:
      http://taskcluster/secrets/v1/secret/project/fuzzing/deploy-npm

  in:
    - $if: 'tasks_for in ["github-pull-request", "github-push"] && !("[skip ci]" in commit_msg)'
      then:
        provisionerId: proj-fuzzing
        workerType: ci
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        scopes:
          - secrets:get:project/fuzzing/deploy-octo
          - secrets:get:project/fuzzing/deploy-npm
        payload:
          maxRunTime: 3600
          image: mozillasecurity/ci-node-14
          features:
            taskclusterProxy: true
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              curl -sL ${octo_deploy_url} | jshon -e secret -e key -u > .ssh/id_ecdsa &&
              chmod 0400 .ssh/id_ecdsa &&
              export NPM_TOKEN=$(curl -sL ${npm_deploy_url} | jshon -e secret -e key -u) &&
              npm set //registry.npmjs.org/:_authToken="$NPM_TOKEN" &&
              set -x &&
              git init repo &&
              cd repo &&
              git remote add origin ${ssh_repo} &&
              git fetch -q --depth=10 origin "${fetch_ref}" &&
              git -c advice.detachedHead=false checkout ${head_rev} &&
              npm i &&
              npm test &&
              HUSKY=0 CI=true npx semantic-release
        metadata:
          name: octo tests node v14
          description: octo tests node v14
          owner: '${event.sender.login}@users.noreply.github.com'
          source: ${http_repo}/raw/${head_rev}/.taskcluster.yml

