version: 1
policy:
  pullRequests: collaborators
tasks:
  $let:
    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    fetch_ref:
      $if: 'tasks_for == "github-pull-request"'
      then: "pull/${event.number}/head"
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: "tags/${event.release.tag_name}"

    http_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}

    ssh_repo:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.base.repo.ssh_url}
      else: ${event.repository.ssh_url}

    git_deploy_url:
      http://taskcluster/secrets/v1/secret/project/fuzzing/deploy-octo
    npm_deploy_url:
      http://taskcluster/secrets/v1/secret/project/fuzzing/deploy-npm

    project_name:
      octo

    user: ${event.sender.login}

  in:
    $if: >
      (tasks_for == "github-push")
      || (tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"])
      || (tasks_for == "github-release" && event["action"] in ["published"])
    then:
      - created: { $fromNow: '' }
        deadline: { $fromNow: '1 hour' }
        provisionerId: proj-fuzzing
        workerType: ci
        payload:
          maxRunTime: 3600
          image: mozillasecurity/ci-node-20
          features:
            taskclusterProxy: true
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              curl -sL ${git_deploy_url} | jshon -e secret -e key -u > .ssh/id_ecdsa &&
              chmod 0400 .ssh/id_ecdsa &&
              export NPM_TOKEN=$(curl -sL ${npm_deploy_url} | jshon -e secret -e key -u) &&
              npm set //registry.npmjs.org/:_authToken="$NPM_TOKEN" &&
              set -x &&
              git init repo &&
              cd repo &&
              git remote add origin ${ssh_repo} &&
              git fetch -q --depth=10 origin "${fetch_ref}" &&
              git -c advice.detachedHead=false checkout ${head_rev} &&
              npm i --no-progress &&
              npm test &&
              HUSKY=0 CI=true npx semantic-release
        scopes:
          - secrets:get:project/fuzzing/deploy-octo
          - secrets:get:project/fuzzing/deploy-npm
        metadata:
          name: ${project_name} ci decision
          description: schedule ci tasks for ${project_name}
          owner: '${user}@users.noreply.github.com'
          source: ${http_repo}/raw/${head_rev}/.taskcluster.yml
    else: []
